In [11]:
import pandas as pd
import json

with open("data/database.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.read_json(json.dumps(data["users"]), orient="index")

In [14]:
display(df.sample(10))

,name,username,verified,followers_count,following_count,tweet_count,listed_count,created_at,location,pages_scraped,next_page_token,profile_image_url,following
249379766,Thomas Jane,ThomasJane,True,83615,1112,1995,581,2011-02-08 22:56:03+00:00,"Silver Lake, CA",0,None,https://pbs.twimg.com/profile_images/141308420...,NaN
832256897709400064,WB Games Support,WBGamesSupport,True,51325,34,33609,76,2017-02-16 15:54:41+00:00,None,0,None,https://pbs.twimg.com/profile_images/120692346...,NaN
288662354,Ryan ten Doeschate,rtendo27,True,161877,871,1431,350,2011-04-27 07:39:04+00:00,None,0,None,https://pbs.twimg.com/profile_images/776738597...,NaN
28635233,DKNY,dkny,True,491156,153,2832,5293,2009-04-03 19:39:35+00:00,"New York, NY",0,None,https://pbs.twimg.com/profile_images/143573226...,NaN
462513479,Skylar Laine James,Skylar_Laine,False,101711,2320,4799,603,2012-01-13 01:21:26+00:00,None,0,None,https://pbs.twimg.com/profile_images/120735645...,NaN
2598371538,EA Play,EAPlay,True,177651,111,18502,638,2014-07-01 18:40:31+00:00,None,0,None,https://pbs.twimg.com/profile_images/136389935...,NaN
2429051735,Navy Football,NavyFB,True,72212,2009,7877,409,2014-03-22 14:53:57+00:00,"Annapolis, MD",0,None,https://pbs.twimg.com/profile_images/146570585...,NaN
918539343811235840,Crime Junkie Podcast,CrimeJunkiePod,True,134141,284,3248,197,2017-10-12 18:10:19+00:00,"Indianapolis, IN",0,None,https://pbs.twimg.com/profile_images/153197165...,NaN
278132803,Zero Skateboards,zeroskateboards,False,59200,48,2153,156,2011-04-06 17:35:14+00:00,None,0,None,https://pbs.twimg.com/profile_images/176432392...,NaN
630523185,rachel,bugposting,False,62003,3758,8691,99,2012-07-08 19:02:12+00:00,boston,4,0,https://pbs.twimg.com/profile_images/152201971...,"[127950286, 448607452, 139617012, 129908108547..."